# Generated by Django 5.2.7 on 2025-10-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('CodeUtilisateur', models.IntegerField(db_column='CodeUtilisateur', primary_key=True, serialize=False)),
                ('IdUtilisateur', models.CharField(db_column='IdUtilisateur', max_length=255)),
                ('Login', models.CharField(blank=True, db_column='Login', max_length=255, null=True)),
                ('MotPasse', models.CharField(blank=True, db_column='MotPasse', max_length=255, null=True)),
                ('Admin', models.CharField(blank=True, db_column='Admin', max_length=1, null=True)),
                ('NomUtilisateur', models.CharField(blank=True, db_column='NomUtilisateur', max_length=255, null=True)),
                ('PrenomUtilisateur', models.CharField(blank=True, db_column='PrenomUtilisateur', max_length=255, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriePatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('taux_reduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Catégorie de Patient',
                'db_table': 'categorie_patient',
            },
        ),
        migrations.CreateModel(
            name='Dentaire',
            fields=[
                ('code_dentaire', models.CharField(db_column='code_dentaire', max_length=25, primary_key=True, serialize=False)),
                ('dentaire', models.CharField(blank=True, max_length=100, null=True)),
                ('pu_dentaire', models.DecimalField(blank=True, db_column='PU_dentaire', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'dentaire',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('codedistrict', models.IntegerField(db_column='CodeDistrict', primary_key=True, serialize=False)),
                ('nomdistrict', models.CharField(blank=True, db_column='NomDistrict', max_length=25, null=True)),
                ('compteurcentre', models.IntegerField(blank=True, db_column='CompteurCentre', null=True)),
                ('codesite', models.IntegerField(blank=True, db_column='CodeSite', null=True)),
                ('sr', models.IntegerField(blank=True, db_column='SR', null=True)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('numdossier', models.CharField(db_column='NumDossier', max_length=25, primary_key=True, serialize=False)),
                ('dateconsultation', models.DateField(blank=True, db_column='dateconsultation', null=True)),
                ('idpatient', models.IntegerField(blank=True, db_column='Idpatient', null=True)),
            ],
            options={
                'db_table': 'dossier',
            },
        ),
        migrations.CreateModel(
            name='Externe',
            fields=[
                ('code_externe', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('consultation_ext', models.CharField(blank=True, db_column='Consultation_ext', max_length=100, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, db_column='Prix_unitaire', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'externe',
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('code_hospital', models.CharField(db_column='Code_hospital', max_length=25, primary_key=True, serialize=False)),
                ('hospitalisation', models.CharField(blank=True, db_column='Hospitalisation', max_length=100, null=True)),
                ('pu_hospitalisation', models.DecimalField(blank=True, db_column='PU_Hospitalisation', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'hospitalisation',
            },
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('code_labo', models.CharField(db_column='code_labo', max_length=25, primary_key=True, serialize=False)),
                ('laboratoire', models.CharField(blank=True, db_column='Laboratoire', max_length=100, null=True)),
                ('pu_hvm', models.DecimalField(blank=True, db_column='PU_HVM', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'laboratoire',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('code_medicament', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('medicament', models.CharField(blank=True, db_column='Medicament', max_length=100, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, db_column='Prix_unitaire', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'medicament',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('code_operation', models.CharField(db_column='Code_operation', max_length=25, primary_key=True, serialize=False)),
                ('operation', models.CharField(blank=True, max_length=100, null=True)),
                ('pu_hrsouvr', models.DecimalField(blank=True, db_column='PU_HrsOuvr', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='Ophtalmologie',
            fields=[
                ('code_ophtamo', models.CharField(db_column='code_ophtamo', max_length=25, primary_key=True, serialize=False)),
                ('opthamologie', models.CharField(blank=True, max_length=100, null=True)),
                ('unitaire_opthalmo', models.CharField(blank=True, max_length=10, null=True)),
                ('pu_ophtalmo', models.DecimalField(blank=True, db_column='PU_ophtalmo', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ophtalmologie',
            },
        ),
        migrations.CreateModel(
            name='PetiteChirurgie',
            fields=[
                ('code_petitchirurgie', models.CharField(db_column='code_petitchirurgie', max_length=25, primary_key=True, serialize=False)),
                ('petite_chirurgie', models.CharField(blank=True, db_column='Petite-chirurgie', max_length=100, null=True)),
                ('hrs_ouvrable', models.DecimalField(blank=True, db_column='Hrs_ouvrable', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'petite_chirurgie',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('coderegion', models.IntegerField(db_column='CodeRegion', primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=19, null=True)),
                ('cle', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='TypePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code Prestation')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de Prestation',
                'verbose_name_plural': 'Types de Prestations',
            },
        ),
        migrations.CreateModel(
            name='Xrays',
            fields=[
                ('code_xrays', models.CharField(db_column='code_xrays', max_length=25, primary_key=True, serialize=False)),
                ('xrays', models.CharField(blank=True, max_length=100, null=True)),
                ('pu_hvm', models.DecimalField(blank=True, db_column='PU_HVM', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'xrays',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('codecommune', models.IntegerField(db_column='CodeCommune', primary_key=True, serialize=False)),
                ('nomcommune', models.CharField(blank=True, db_column='NomCommune', max_length=26, null=True)),
                ('codedistrict', models.ForeignKey(blank=True, db_column='CodeDistrict', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.district')),
                ('coderegion', models.ForeignKey(blank=True, db_column='CodeRegion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.region')),
            ],
            options={
                'db_table': 'commune',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('numfacture', models.CharField(db_column='NumFacture', max_length=50, primary_key=True, serialize=False)),
                ('datefacture', models.DateField(blank=True, db_column='DateFacture', null=True)),
                ('montantfacture', models.DecimalField(blank=True, db_column='MontantFacture', decimal_places=2, max_digits=10, null=True)),
                ('codeutilisateur', models.ForeignKey(blank=True, db_column='CodeUtilisateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.utilisateur')),
                ('numdossier', models.ForeignKey(blank=True, db_column='NumDossier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.dossier')),
            ],
            options={
                'db_table': 'facture',
            },
        ),
        migrations.CreateModel(
            name='DetailFacture',
            fields=[
                ('iddetailfacture', models.AutoField(db_column='IdDetailfacture', primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, db_column='Designation', max_length=100, null=True)),
                ('abr_table', models.CharField(blank=True, max_length=1, null=True)),
                ('pu', models.DecimalField(blank=True, db_column='PU', decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.DecimalField(blank=True, db_column='Quantite', decimal_places=2, max_digits=10, null=True)),
                ('numfacture', models.ForeignKey(blank=True, db_column='Numfacture', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.facture')),
            ],
            options={
                'db_table': 'detailfacture',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('numpaiement', models.CharField(db_column='NumPaiement', max_length=100, primary_key=True, serialize=False)),
                ('datepaiement', models.DateField(blank=True, db_column='datepaiement', null=True)),
                ('numpatient', models.CharField(blank=True, db_column='Numpatient', max_length=25, null=True)),
                ('codeutilisateur', models.ForeignKey(blank=True, db_column='CodeUtilisateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.utilisateur')),
            ],
            options={
                'db_table': 'paiement',
            },
        ),
        migrations.CreateModel(
            name='DetailPaiement',
            fields=[
                ('iddetailpaiement', models.AutoField(db_column='Iddetailpaiement', primary_key=True, serialize=False)),
                ('iddetailfacture', models.ForeignKey(blank=True, db_column='IdDetailfacture', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.detailfacture')),
                ('numpaiement', models.ForeignKey(blank=True, db_column='NumPaiement', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.paiement')),
            ],
            options={
                'db_table': 'detailpaiement',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='coderegion',
            field=models.ForeignKey(blank=True, db_column='CodeRegion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.region'),
        ),
        migrations.CreateModel(
            name='TypeConsultation',
            fields=[
                ('idtype', models.AutoField(db_column='IdType', primary_key=True, serialize=False)),
                ('abr_consultation', models.CharField(db_column='Abr_consultation', max_length=1)),
                ('type_consultation', models.CharField(blank=True, db_column='Type_consultation', max_length=25, null=True)),
            ],
            options={
                'db_table': 'type_consultation',
                'unique_together': {('idtype', 'abr_consultation')},
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='idtype',
            field=models.ForeignKey(blank=True, db_column='IdType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.typeconsultation'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idpatient', models.AutoField(db_column='Idpatient', primary_key=True, serialize=False)),
                ('numpatient', models.CharField(db_column='NumPatient', max_length=25)),
                ('nompatient', models.CharField(blank=True, db_column='NomPatient', max_length=100, null=True)),
                ('prenompatient', models.CharField(blank=True, db_column='PrenomPatient', max_length=100, null=True)),
                ('sexe_patient', models.CharField(blank=True, db_column='SexePatient', max_length=1, null=True)),
                ('categorie', models.ForeignKey(blank=True, db_column='categorie_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_patient.categoriepatient')),
                ('codecommune', models.ForeignKey(blank=True, db_column='CodeCommune', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.commune')),
                ('codedistrict', models.ForeignKey(blank=True, db_column='CodeDitrict', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.district')),
                ('codeutilisateur', models.ForeignKey(blank=True, db_column='CodeUtilisateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.utilisateur')),
                ('coderegion', models.ForeignKey(blank=True, db_column='CodeRegion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_patient.region')),
            ],
            options={
                'db_table': 'patient',
                'unique_together': {('idpatient', 'numpatient')},
            },
        ),
    ]
